#!/usr/bin/env python3
"""Regenerate STATUS.md from what actually exists.

Never hand-edit STATUS.md: this script derives every checkbox from the
published pages, so the tracker cannot drift from reality. A state's
baseline box is checked when site/states/<slug>.html exists; its full-page
box is checked when that page carries the notice-periods section ("Notice
periods and deadlines, as stated in the sources"), which only full pages
have. The last-checked date is read from the page's docket.

Run from the project root (transfer-safeguards):
    python3 tools/build-status.py
"""

import datetime
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE_STATES = ROOT / "site" / "states"
FEDERAL = ROOT / "site" / "federal.html"
OUT = ROOT / "STATUS.md"

# Canonical slugs for all 51 jurisdictions. Page files and site hrefs use
# these exact slugs; multi-word states are hyphenated.
JURISDICTIONS = [
    ("Alabama", "alabama"), ("Alaska", "alaska"), ("Arizona", "arizona"),
    ("Arkansas", "arkansas"), ("California", "california"),
    ("Colorado", "colorado"), ("Connecticut", "connecticut"),
    ("Delaware", "delaware"), ("District of Columbia", "district-of-columbia"),
    ("Florida", "florida"), ("Georgia", "georgia"), ("Hawaii", "hawaii"),
    ("Idaho", "idaho"), ("Illinois", "illinois"), ("Indiana", "indiana"),
    ("Iowa", "iowa"), ("Kansas", "kansas"), ("Kentucky", "kentucky"),
    ("Louisiana", "louisiana"), ("Maine", "maine"), ("Maryland", "maryland"),
    ("Massachusetts", "massachusetts"), ("Michigan", "michigan"),
    ("Minnesota", "minnesota"), ("Mississippi", "mississippi"),
    ("Missouri", "missouri"), ("Montana", "montana"), ("Nebraska", "nebraska"),
    ("Nevada", "nevada"), ("New Hampshire", "new-hampshire"),
    ("New Jersey", "new-jersey"), ("New Mexico", "new-mexico"),
    ("New York", "new-york"), ("North Carolina", "north-carolina"),
    ("North Dakota", "north-dakota"), ("Ohio", "ohio"),
    ("Oklahoma", "oklahoma"), ("Oregon", "oregon"),
    ("Pennsylvania", "pennsylvania"), ("Rhode Island", "rhode-island"),
    ("South Carolina", "south-carolina"), ("South Dakota", "south-dakota"),
    ("Tennessee", "tennessee"), ("Texas", "texas"), ("Utah", "utah"),
    ("Vermont", "vermont"), ("Virginia", "virginia"),
    ("Washington", "washington"), ("West Virginia", "west-virginia"),
    ("Wisconsin", "wisconsin"), ("Wyoming", "wyoming"),
]

FULL_MARKER = "Notice periods and deadlines, as stated in the sources"
CHECKED_RE = re.compile(r'docket-checked[^>]*>\s*([^<]+?)\s*<')

# Translated pages live beside their English page as <slug>.es.html. The
# Spanish column is derived the same way every other box is: from what is
# actually published, never from intent.
LANGS = [("es", "Spanish")]


def main():
    rows = []
    n_base = n_full = 0
    n_lang = {code: 0 for code, _ in LANGS}
    for name, slug in JURISDICTIONS:
        page = SITE_STATES / f"{slug}.html"
        base = page.exists()
        full = False
        checked = ""
        if base:
            text = page.read_text(encoding="utf-8")
            full = FULL_MARKER in text
            m = CHECKED_RE.search(text)
            checked = m.group(1) if m else ""
        langs = {}
        for code, _ in LANGS:
            have = (SITE_STATES / f"{slug}.{code}.html").exists()
            langs[code] = have
            n_lang[code] += have
        n_base += base
        n_full += full
        rows.append((name, slug, base, full, checked, langs))

    # The federal page counts as built only when it carries a docket —
    # a pre-build placeholder page does not.
    federal_built = FEDERAL.exists() and '<dl class="docket"' in FEDERAL.read_text(encoding="utf-8")
    today = datetime.date.today().isoformat()
    box = lambda v: "[x]" if v else "[ ]"
    n = len(JURISDICTIONS)
    lang_counts = " · ".join(
        f"{label}: {n_lang[code]} of {n}" for code, label in LANGS)
    lines = [
        "# transfer-safeguards — coverage status",
        "",
        f"Generated by tools/build-status.py on {today}. Do not edit by hand;",
        "every checkbox is derived from the published pages in site/states/.",
        "Baseline = docket layer published. Full = notice-periods section",
        "present. Spanish = a translated page is published; it carries the",
        "docket, the hoisted rows, and the notice periods and deadlines, in",
        "the state's own published translation only.",
        "",
        f"**Baseline: {n_base} of {n} · Full pages: {n_full} of {n} · {lang_counts}"
        f" · Federal layer: {'built' if federal_built else 'pending'}**",
        "",
        "| State | Baseline | Full page | "
        + " | ".join(label for _, label in LANGS)
        + " | Sources last checked |",
        "|---|:---:|:---:|" + ":---:|" * len(LANGS) + "---|",
    ]
    for name, slug, base, full, checked, langs in rows:
        label = f"[{name}](site/states/{slug}.html)" if base else name
        cells = []
        for code, _ in LANGS:
            if langs[code]:
                cells.append(f"[[x]](site/states/{slug}.{code}.html)")
            else:
                cells.append("[ ]")
        lines.append(f"| {label} | {box(base)} | {box(full)} | "
                     + " | ".join(cells) + f" | {checked} |")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    extra = "".join(f", {code} {n_lang[code]}/{n}" for code, _ in LANGS)
    print(f"STATUS.md written: baseline {n_base}/{n}, full {n_full}/{n}{extra}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
