#!/usr/bin/env python3
"""Regenerate the state-abbreviation picker on the homepage and the states index.

Renders a static (no-JavaScript-required) grid of postal abbreviations —
one per jurisdiction, alphabetical. A published state's abbreviation is a
direct link to its page. An unpublished state's abbreviation renders as a
muted, non-interactive pill so the full 51-jurisdiction shape of the project
stays visible without implying a page exists yet.

"Published" is read straight from site/states/<slug>.html on disk — same
source of truth as tools/build-status.py — so this can never drift from
what's actually live. Route status and last-checked date for the tooltip on
published pills come from the STATES:BEGIN/END JSON block already
maintained in site/index.html as part of each state's build.

Injects between HTML comment markers:
    <!-- STATE-PICKER:BEGIN --> ... <!-- STATE-PICKER:END -->
in both site/index.html and site/states/index.html. Never hand-edit the
picker markup between those markers — it is overwritten on every run.

Run from the project root (transfer-safeguards):
    python3 tools/build-state-picker.py
"""

import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
SITE_STATES = SITE / "states"
HOME = SITE / "index.html"
STATES_INDEX = SITE_STATES / "index.html"

# Canonical (name, slug, USPS-style abbreviation) for all 51 jurisdictions,
# alphabetical by name. Must stay in sync with tools/build-status.py's
# JURISDICTIONS list.
JURISDICTIONS = [
    ("Alabama", "alabama", "AL"), ("Alaska", "alaska", "AK"),
    ("Arizona", "arizona", "AZ"), ("Arkansas", "arkansas", "AR"),
    ("California", "california", "CA"), ("Colorado", "colorado", "CO"),
    ("Connecticut", "connecticut", "CT"), ("Delaware", "delaware", "DE"),
    ("District of Columbia", "district-of-columbia", "DC"),
    ("Florida", "florida", "FL"), ("Georgia", "georgia", "GA"),
    ("Hawaii", "hawaii", "HI"), ("Idaho", "idaho", "ID"),
    ("Illinois", "illinois", "IL"), ("Indiana", "indiana", "IN"),
    ("Iowa", "iowa", "IA"), ("Kansas", "kansas", "KS"),
    ("Kentucky", "kentucky", "KY"), ("Louisiana", "louisiana", "LA"),
    ("Maine", "maine", "ME"), ("Maryland", "maryland", "MD"),
    ("Massachusetts", "massachusetts", "MA"), ("Michigan", "michigan", "MI"),
    ("Minnesota", "minnesota", "MN"), ("Mississippi", "mississippi", "MS"),
    ("Missouri", "missouri", "MO"), ("Montana", "montana", "MT"),
    ("Nebraska", "nebraska", "NE"), ("Nevada", "nevada", "NV"),
    ("New Hampshire", "new-hampshire", "NH"), ("New Jersey", "new-jersey", "NJ"),
    ("New Mexico", "new-mexico", "NM"), ("New York", "new-york", "NY"),
    ("North Carolina", "north-carolina", "NC"),
    ("North Dakota", "north-dakota", "ND"), ("Ohio", "ohio", "OH"),
    ("Oklahoma", "oklahoma", "OK"), ("Oregon", "oregon", "OR"),
    ("Pennsylvania", "pennsylvania", "PA"),
    ("Rhode Island", "rhode-island", "RI"),
    ("South Carolina", "south-carolina", "SC"),
    ("South Dakota", "south-dakota", "SD"), ("Tennessee", "tennessee", "TN"),
    ("Texas", "texas", "TX"), ("Utah", "utah", "UT"),
    ("Vermont", "vermont", "VT"), ("Virginia", "virginia", "VA"),
    ("Washington", "washington", "WA"),
    ("West Virginia", "west-virginia", "WV"),
    ("Wisconsin", "wisconsin", "WI"), ("Wyoming", "wyoming", "WY"),
]

BEGIN = "<!-- STATE-PICKER:BEGIN — generated by tools/build-state-picker.py, do not hand-edit -->"
END = "<!-- STATE-PICKER:END -->"


def read_state_index_json():
    """Pull checked-date/status per slug from site/index.html's STATES JSON."""
    text = HOME.read_text(encoding="utf-8")
    m = re.search(
        r'<script type="application/json" id="state-index">\s*(\[.*?\])\s*</script>',
        text, re.S,
    )
    if not m:
        return {}
    try:
        records = json.loads(m.group(1))
    except json.JSONDecodeError:
        return {}
    return {r["slug"]: r for r in records}


def render_picker(meta, base):
    """base: '' for homepage (hrefs like states/al.html), '' for states/index.html (hrefs like al.html) — pass the href prefix."""
    parts = ['<div class="state-picker" role="group" aria-label="Jump to a state page">']
    for name, slug, abbr in JURISDICTIONS:
        page = SITE_STATES / f"{slug}.html"
        if page.exists():
            rec = meta.get(slug)
            checked = rec.get("checked") if rec else None
            title = f"{name} — sources last checked {checked}" if checked else name
            parts.append(
                f'<a class="state-pill" href="/states/{slug}/" title="{html.escape(title)}">'
                f'{abbr}<span class="sr-only">{html.escape(name)}</span></a>'
            )
        else:
            title = f"{name} — not yet published"
            parts.append(
                f'<span class="state-pill state-pill--pending" title="{html.escape(title)}">'
                f'{abbr}<span class="sr-only">{html.escape(name)} — not yet published</span></span>'
            )
    parts.append("</div>")
    return "\n".join(parts)


def inject(path, block, count):
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    replacement = BEGIN + "\n" + block + "\n" + END
    if not pattern.search(text):
        print(f"ERROR: markers not found in {path}", file=sys.stderr)
        return False
    text = pattern.sub(replacement, text, count=1)
    text = re.sub(
        r'(<span id="picker-count">)\d+(</span>)',
        rf'\g<1>{count}\g<2>',
        text,
    )
    path.write_text(text, encoding="utf-8")
    return True


def main():
    meta = read_state_index_json()
    published = sum(1 for _, slug, _ in JURISDICTIONS if (SITE_STATES / f"{slug}.html").exists())

    ok1 = inject(HOME, render_picker(meta, "states/"), published)
    ok2 = inject(STATES_INDEX, render_picker(meta, ""), published)

    if ok1 and ok2:
        print(f"State picker regenerated on both pages — {published}/{len(JURISDICTIONS)} published.")
        return 0
    return 1


if __name__ == "__main__":
    sys.exit(main())
